language: android

android:
  components:
    - platform-tools-28.0.2
    - tools
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-android-28
    - extra

before_install:
  - chmod +x gradlew

script:
  - "yes | sdkmanager --licenses"
  - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
